// next component imports
import Head from "next/head";
import Image from "next/image";

// component Imports
import Header from "../components/Header/Header";
import DatabizLogoSVG from "../components/SVG/DatabizLogoSVG";
import AudiophileLogoSVG from "../components/SVG/AudiophileLogoSVG";
import MeetLogoSVG from "../components/SVG/MeetLogoSVG";

// Custom Hooks imports
import useMediaQuery from "../components/Hooks/UseMediaQuery";

// Image Imports
import heroImageDesktop from "../public/images/image-hero-desktop.png";
import heroImageMobile from "../public/images/image-hero-mobile.png";

export default function Home() {
  const isBreakpoint = useMediaQuery(375);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <section>
          <h1>Make remote work</h1>
          <p>
            Get your team in sync, no matter your location. Streamline
            processes, create team rituals, and watch productivity soar.
          </p>
          <a href="#">Learn more</a>
          <ul>
            <li>
              <DatabizLogoSVG />
            </li>
            <li>
              <AudiophileLogoSVG />
            </li>
            <li>
              <MeetLogoSVG />
            </li>
          </ul>
        </section>
        <section>
          {isBreakpoint ? (
            <Image src={heroImageMobile} alt="man using laptop" />
          ) : (
            <Image src={heroImageDesktop} alt="man using laptop" />
          )}
        </section>
      </main>
    </div>
  );
}
